Sign up feature completed; sign up with correct field values and user…
dimitritsampiras/olympian pull request #108
Opened 2022-11-30 17:43 UTC by MatthewWMcC

… is redirected to login page; comprehensive error checking ensures all sign up values are correct

2022-11-30 21:47 UTC, bentvelj commented
UX is consistent with login which is great. I think we should add little icons to the fields, but that's for another ticket.

2022-12-01 08:10 UTC, MatthewWMcC commented
Refactored to use formik error handling. Please look at this branch again.

2022-12-01 18:43 UTC, bentvelj requested changes

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                    {touched.name && !!errors.name && (
```suggestion
                    {touched.name && errors.name && (
```
Nit: Unnecessary cast

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                    {touched.username && !!errors.username && (
```suggestion
                    {touched.username && errors.username && (
```

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                    {touched.email && !!errors.email && (
```suggestion
                    {touched.email && errors.email && (
```

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                    {touched.password && !!errors.password && (
```suggestion
                    {touched.password && errors.password && (
```

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.email && !!errors.email}
```suggestion
                      error={touched.email && errors.email}
```

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.username && !!errors.username}
```suggestion
                      error={touched.username && errors.username}
```

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.name && !!errors.name}
```suggestion
                      error={touched.name && errors.name}
```

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.password && !!errors.password}
```suggestion
                      error={touched.password && errors.password}
```

2022-12-01 18:43 UTC, bentvelj commented on src/athena/src/components/screens/auth/SignUp.tsx
> +  errorMessageStyle: {
May be beneficial to create an ErrorMessage component that we can reuse

2022-12-01 18:43 UTC, bentvelj commented on src/hermes/package.json
> +    "prisma": "^4.7.0",
Reason why Prisma is a dev dependency now?

2022-12-01 18:43 UTC, bentvelj commented on src/hermes/src/app.ts
> +  // prisma.user.create({
Remove this

2022-12-01 18:47 UTC, bentvelj commented on src/hermes/src/server/schema/User/helpers/authentication.ts
> +  }
I don't think this explicit check is necessary, I think we should specify username (and email) as `@unique` in the prisma schema, and then it should reject the query automatically

2022-12-01 18:47 UTC, bentvelj commented on src/hermes/src/app.ts
> +  // });
Delete this

2022-12-01 19:31 UTC, MatthewWMcC commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.username && !!errors.username}
is necessary to avoid typeError

2022-12-01 19:31 UTC, MatthewWMcC commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.name && !!errors.name}
is necessary to avoid typeError

2022-12-01 19:32 UTC, MatthewWMcC commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.password && !!errors.password}
is necessary to avoid typeError

2022-12-01 19:33 UTC, MatthewWMcC commented on src/athena/src/components/screens/auth/SignUp.tsx
> +                      error={touched.email && !!errors.email}
is necessary to avoid typeError

2022-12-01 19:33 UTC, MatthewWMcC commented on src/athena/src/components/screens/auth/SignUp.tsx
> +  errorMessageStyle: {
out of scope for ticket

2022-12-01 19:50 UTC, merged