Doc/vnv/system test
dimitritsampiras/olympian pull request #64
Opened 2022-10-31 21:24 UTC by Wililee

Please read them, 

These are the functional requirement system tests.
Test IDs will be placed at a later date.

![image](https://user-images.githubusercontent.com/47044936/199113061-b75a2fdc-3bf6-42f6-bf94-a3e726ee5a0b.png)
![image](https://user-images.githubusercontent.com/47044936/199113083-ed08d662-a139-449e-b812-90462da88262.png)
![image](https://user-images.githubusercontent.com/47044936/199113162-2a2815c2-9bee-4d52-a283-a431e5b76450.png)
![image](https://user-images.githubusercontent.com/47044936/199113181-d0fea309-bb4d-4677-8e16-a63f48b96005.png)
![image](https://user-images.githubusercontent.com/47044936/199113194-17366f4e-fc76-4ea2-b6f4-bdc200ee45d9.png)
![image](https://user-images.githubusercontent.com/47044936/199113210-0397f5d5-6c18-4cf0-bb55-447753745bfa.png)
![image](https://user-images.githubusercontent.com/47044936/199113227-16e64226-3156-40f7-9f75-2ea4280380a2.png)
![image](https://user-images.githubusercontent.com/47044936/199113252-a37a4090-fc8c-4cb5-916f-0159391f269a.png)
![image](https://user-images.githubusercontent.com/47044936/199113264-c49eb19d-b4fc-47bb-9a5f-4e0deae2b270.png)
![image](https://user-images.githubusercontent.com/47044936/199113286-f0e707da-962a-43a3-9eff-214daa6f5fbd.png)
![image](https://user-images.githubusercontent.com/47044936/199113299-ed368bf4-97e4-4bf2-9c20-5ee85fb595ef.png)
![image](https://user-images.githubusercontent.com/47044936/199113309-d420b4cf-9e8f-46d9-a22e-c5ca61fd8a36.png)
![image](https://user-images.githubusercontent.com/47044936/199113326-2dac887b-b05d-4fe6-9c86-880542de0df7.png)
![image](https://user-images.githubusercontent.com/47044936/199113342-e5fe8560-bf42-4dc6-9314-21331967ea18.png)
![image](https://user-images.githubusercontent.com/47044936/199113359-ca21823a-6197-465f-9848-6c0b04a77dcb.png)
![image](https://user-images.githubusercontent.com/47044936/199113375-8dba0eea-a10c-46bd-8229-340ad6ed262d.png)
![image](https://user-images.githubusercontent.com/47044936/199113404-8aff1db8-8aad-4ff3-b061-2e7f97486278.png)

2022-11-01 22:56 UTC, dimitritsampiras commented
I think you should categorize these tests under specific "Areas"

2022-11-02 00:12 UTC, bentvelj requested changes
Some typos but looks fantastic

2022-11-02 00:12 UTC, bentvelj commented on docs/VnVPlan/VnVPlan.tex
> +		Input: a user created exercise with the parameters required for the exercise.
```suggestion
		Input: A user created exercise with the parameters required for the exercise.
```

2022-11-02 00:12 UTC, bentvelj commented on docs/VnVPlan/VnVPlan.tex
> +		How test will be performed: The test will be preformed by manually added exercises to a workout routine until the limit. Then upon adding the limiting input, a notification should be expected.
```suggestion
		How test will be performed: The test will be preformed by manually added exercises to a workout routine until the limit. Then upon adding the limiting input, a notification is expected.
```

2022-11-02 00:12 UTC, bentvelj commented on docs/VnVPlan/VnVPlan.tex
> +		Input: An edit or addition to a workout routine to make is public.
```suggestion
		Input: An edit or addition to a workout routine to make it public.
```

2022-11-02 00:12 UTC, bentvelj commented on docs/VnVPlan/VnVPlan.tex
> +		Test Case Derivation: All workout routine that follow match a search, should be display.
```suggestion
		Test Case Derivation: All workout routines that match a search, should be displayed.
```

2022-11-02 00:21 UTC, bentvelj approved these changes
LGTM

2022-11-02 00:21 UTC, merged